spring:
  datasource:
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.web: WARN