spring:
  application:
    name: blocker-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/certs

server:
  port: 8087
  address: 0.0.0.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

blocker:
  maintenance:
    start: "00:00"
    end: "00:05"