spring:
  application:
    name: exchange-generator

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: exchange_generator_service

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: exchange_generator_service
    drop-first: true
    clear-checksums: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak-service:
            provider: keycloak
            client-id: front-ui-service
            client-secret: z1GkjE1Vi9Ba1B91tFPjZtg6CGQiw5ea
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/token
            authorization-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/auth

server:
  port: 8084
  address: 0.0.0.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  level:
    root: info
    org.springframework.security: trace
    org.springframework.web: debug
    org.springframework.security.oauth2: trace
