spring:
  application:
    name: front-ui

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: front-ui
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

          keycloak-admin:
            provider: keycloak
            client-id: front-ui-service
            client-secret: z1GkjE1Vi9Ba1B91tFPjZtg6CGQiw5ea
            authorization-grant-type: client_credentials

        provider:
          keycloak:
            authorization-uri: http://localhost:8082/realms/bank-realm/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username

server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: native

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.github.maximslepukhin: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.client.web: TRACE
    org.springframework.security.oauth2.client.endpoint: TRACE
    org.springframework.security.web.authentication: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    com.github.maximslepukhin.controller: INFO

gateway:
  url: http://gateway:8080