apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts-db.fullname" . }}-secret
type: Opaque
stringData:
  username: "{{ .Values.postgres.user }}"
  password: "{{ .Values.postgres.password }}"
