apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "accounts-db.fullname" . }}
  labels:
    app: {{ include "accounts-db.name" . }}
spec:
  serviceName: {{ include "accounts-db.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "accounts-db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "accounts-db.name" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "accounts-db.fullname" . }}-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "accounts-db.fullname" . }}-secret
                  key: password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-schemas
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: init-schemas
          configMap:
            name: {{ include "accounts-db.fullname" . }}-init-schemas
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
