# Берем официальный Jenkins с OpenJDK 21
FROM jenkins/jenkins:2.528.2-jdk21

# Переключаемся на root для установки пакетов
USER root

# Обновляем репозитории и устанавливаем базовые утилиты
RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    wget \
    gnupg \
    lsb-release \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем Maven
ARG MAVEN_VERSION=3.9.5
RUN wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.zip \
    && unzip apache-maven-${MAVEN_VERSION}-bin.zip -d /opt/ \
    && rm apache-maven-${MAVEN_VERSION}-bin.zip \
    && ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/bin/mvn

# Устанавливаем Docker CLI
RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

# Устанавливаем Kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

# Устанавливаем Helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Даем Jenkins права на Docker (если понадобятся)
RUN usermod -aG docker jenkins

# Возвращаемся на пользователя jenkins
USER jenkins

# Устанавливаем переменные окружения (по желанию)
ENV MAVEN_HOME=/opt/apache-maven-${MAVEN_VERSION}
ENV PATH=$MAVEN_HOME/bin:$PATH
