version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-bank
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d   # ⚡ скрипты инициализации схем

  accounts-service:
    build:
      context: .
      dockerfile: accounts-service/Dockerfile
    container_name: accounts-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankdb
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bankpass
      SPRING_LIQUIBASE_CLEAR-CHECKSUMS: "true"
    depends_on:
      - postgres

  front-ui:
    build:
      context: ./front-ui
      dockerfile: Dockerfile
    container_name: front-ui
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankdb
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bankpass

volumes:
  postgres-data: