FROM jenkins/jenkins:lts-jdk17

USER root

# Установим curl и bash (если ещё не установлены)
RUN apt-get update && apt-get install -y curl bash

# Установим kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# Установим helm
RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

# Установим docker CLI
RUN apt-get update && apt-get install -y docker.io

USER jenkins
