apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 6443
      protocol: TCP
      nodePort: 30000  # Порт, через который будет доступен API
  selector:
    component: kube-apiserver
  type: NodePort
