spring:
  application:
    name: exchange-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:80/realms/bank-realm
          jwk-set-uri: http://keycloak:80/realms/bank-realm/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: my-kafka.default.svc.cluster.local:9092
    consumer:
      group-id: exchange-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.github.maximslepukhin.model.dto"
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: >
          org.apache.kafka.common.security.scram.ScramLoginModule required
          username="user1"
          password="hA6uwPNxFI";

server:
  port: 8084
  address: 0.0.0.0

logging:
  level:
    root: info
    org.springframework.security: trace
    org.springframework.web: debug
    org.springframework.security.oauth2: trace
