apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-service-config
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}?currentSchema={{ .Values.postgres.schema }}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "{{ .Values.postgres.schema }}"
  SPRING_LIQUIBASE_DEFAULT_SCHEMA: "{{ .Values.postgres.schema }}"
