spring:
  application:
    name: cash-service

  kafka:
    bootstrap-servers: my-kafka.default.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:80/realms/bank-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak-service:
            client-id: front-ui-service
            client-secret: z1GkjE1Vi9Ba1B91tFPjZtg6CGQiw5ea
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:80/realms/bank-realm/protocol/openid-connect/token

server:
  port: 8091
  address: 0.0.0.0

logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: TRACE

clients:
  accounts-service-url: ${ACCOUNTS_SERVICE_URL}
  blocker-service-url: ${BLOCKER_SERVICE_URL}
  notifications-service-url: ${NOTIFICATIONS_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    enable:
      all: true

  tracing:
    sampling:
      probability: 1

  zipkin:
    tracing:
      endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans