spring:
  application:
    name: cash-service

  kafka:
    bootstrap-servers: my-kafka.default.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:80/realms/bank-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak-service:
            client-id: front-ui-service
            client-secret: z1GkjE1Vi9Ba1B91tFPjZtg6CGQiw5ea
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:80/realms/bank-realm/protocol/openid-connect/token

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: cash_service

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/cash-service/master.yaml
    drop-first: false
    clear-checksums: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8091
  address: 0.0.0.0
  shutdown: graceful

logging:
  level:
    root: INFO
    com.github.maximslepukhin: INFO
    org.springframework: WARN

clients:
  accounts-service-url: ${ACCOUNTS_SERVICE_URL}
  blocker-service-url: ${BLOCKER_SERVICE_URL}
  notifications-service-url: ${NOTIFICATIONS_SERVICE_URL}

resilience4j:
  circuitbreaker:
    instances:
      accountsService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      blockerService:
        slidingWindowSize: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 10s
  retry:
    instances:
      accountsService:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
  timelimiter:
    instances:
      accountsService:
        timeoutDuration: 3s
      blockerService:
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    enable:
      all: true

  tracing:
    sampling:
      probability: 1

  zipkin:
    tracing:
      endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans
