replicaCount: 1

image:
  repository: notifications-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8087
  targetPort: 8087
  labels:
    app.kubernetes.io/name: notifications-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8087"

resources: {}

env:
  SPRING_PROFILES_ACTIVE: "dev"
  POSTGRES_HOST: "accounts-db-accounts-db"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "accountsdb"
  POSTGRES_USERNAME: "accounts_user"
  POSTGRES_PASSWORD: "strongpassword123"
  POSTGRES_SCHEMA: "notifications_service"

postgres:
  host: "accounts-db-accounts-db"
  port: 5432
  database: "accountsdb"
  username: "accounts_user"
  password: "strongpassword123"
  schema: "notifications_service"

keycloak:
  jwkSetUri: "http://keycloak:80/realms/bank-realm/protocol/openid-connect/certs"

secrets:
  POSTGRES_USERNAME: "admin"
  POSTGRES_PASSWORD: "password"
  KEYCLOAK_CLIENTSECRET: "z1GkjE1Vi9Ba1B91tFPjZtg6CGQiw5ea"

logging:
  level:
    root: info