apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exchange-service.fullname" . }}
  labels:
    app: {{ include "exchange-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "exchange-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "exchange-service.name" . }}
    spec:
      containers:
        - name: exchange-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: 9013
              name: jmx
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dcom.sun.management.jmxremote=true
                -Dcom.sun.management.jmxremote.port=9013
                -Dcom.sun.management.jmxremote.rmi.port=9013
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.ssl=false
                -Djava.rmi.server.hostname=127.0.0.1
          resources: {{- toYaml .Values.resources | nindent 12 }}
