spring:
  application:
    name: exchange-generator

  kafka:
    bootstrap-servers: my-kafka.default.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  zipkin:
    tracing:
      endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1  # трассируем 100% запросов