spring:
  application:
    name: exchange-generator

  kafka:
    bootstrap-servers: my-kafka.default.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans  # эндпоинт Zipkin
  tracing:
    sampling:
      probability: 1  # трассируем 100% запросов