spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: lb://ACCOUNTS-SERVICE
          predicates:
            - Path=/accounts-service/**
        - id: cash-service
          uri: lb://CASH-SERVICE
          predicates:
            - Path=/cash-service/**
        - id: transfer-service
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/transfer-service/**
        - id: exchange-service
          uri: lb://EXCHANGE-SERVICE
          predicates:
            - Path=/exchange-service/**
        - id: blocker-service
          uri: lb://BLOCKER-SERVICE
          predicates:
            - Path=/blocker-service/**
        - id: notifications-service
          uri: lb://NOTIFICATIONS-SERVICE
          predicates:
            - Path=/notifications-service/**
        - id: front-ui
          uri: lb://FRONT-UI
          predicates:
            - Path=/front-ui/**
      default-filters:
        - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8082
  address: 0.0.0.0
