replicaCount: 1

service:
  type: ClusterIP
  port: 5601

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

elasticsearchHosts: "http://elasticsearch-master.default.svc.cluster.local:9200"
