spring:
  application:
    name: front-ui
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5s
    cache-names: rates

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8080
  address: 0.0.0.0
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    enable:
      all: true

  tracing:
    sampling:
      probability: 1

  zipkin:
    tracing:
      endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      accountsService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      blockerService:
        slidingWindowSize: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 10s
      cashService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      transferService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      exchangeService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      accountsService:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
  timelimiter:
    instances:
      accountsService:
        timeoutDuration: 3s
      cashService:
        timeoutDuration: 10s

logging:
  level:
    root: INFO
    com.github.maximslepukhin: INFO
    org.springframework: WARN
    org.keycloak: WARN
