spring:
  application:
    name: front-ui
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  zipkin:
    tracing:
      endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1  # трассируем 100% запросов

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.core: TRACE
    org.springframework.security.oauth2.client.userinfo: TRACE
    org.springframework.security.oauth2.core.endpoint: DEBUG
    org.keycloak: DEBUG
    org.keycloak.adapters: DEBUG