{
 "title": "JVM Overview (Micrometer OTLP)",
 "description": "Dashboard for JVM metrics with Spring Boot OTLP metric exporter",
 "tags": [
  "JVM",
  "open-telemetry",
  "Java",
  "otel",
  "opentelemetry",
  "otlp",
  "Spring",
  "Boot",
  "Spring Boot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(jvm_classes_loaded,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Request rate of HTTP server requests",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "description": "Ratio of HTTP server requests that have returned a 5xx error code",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (instance)(rate(http_server_requests_count{job=~\"$job\", instance=~\"$instance\", outcome=\"SERVER_ERROR\"}[$__rate_interval]))) / on (instance) (sum by (instance)(rate(http_server_requests_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "95% percentile of HTTP server request duration ",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum by(le, instance) (rate(http_server_requests_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization for the whole system",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Utilization",
   "type": "timeseries",
   "description": "How much of the available heap memory is used",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used{job=~\"$job\",area=\"heap\", instance=~\"$instance\"}) / on(instance) sum by (instance) (jvm_memory_max{job=~\"$job\",area=\"heap\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "description": "Percentage of pause time spend for garbage collection pauses",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(jvm_gc_pause_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "timeseries",
   "description": "Number of currently loaded classes",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of currently executing (also called \"live\") threads (both daemon and non-daemon)",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_live{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}