{{- if .Values.realmImport.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
data:
  {{ .Values.realmImport.file }}: |-
    {{ .Files.Get "files/bank-realm-realm.json" | nindent 4 }}
    {{ .Files.Get "files/bank-realm-гыукы-0.json" | nindent 4 }}
{{- end }}
