apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
stringData:
  admin-username: "{{ .Values.admin.username }}"
  admin-password: "{{ .Values.admin.password }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  username: "{{ .Values.postgres.username }}"
  password: "{{ .Values.postgres.password }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: "{{ .Files.Get "tls.crt" | b64enc }}"
  tls.key: "{{ .Files.Get "tls.key" | b64enc }}"