  {{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
stringData:
  admin-username: "admin"
  admin-password: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  username: "keycloak"
  password: "keycloak"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/tls.key" | b64enc }}
  {{- end }}