pipeline {
    agent {
        docker {
            image 'jenkins-k8s'
            args """
                -v /Users/maksim/.kube:/var/jenkins_home/.kube:ro
                -v /Users/maksim/.minikube:/var/jenkins_home/.minikube:ro
                -v /var/run/docker.sock:/var/run/docker.sock
            """
        }
    }

    environment {
        SERVICE_NAME = 'transfer-service'
        HELM_CHART_PATH = './helm/bankapp/charts/transfer-service'
        ORIGINAL_KUBECONFIG = '/var/jenkins_home/.kube/config'
        KUBECONFIG = '/tmp/kubeconfig'
        MINIKUBE_HOME = '/var/jenkins_home/.minikube'
    }

    stages {
        stage('Clean Workspace') { steps { deleteDir() } }
        stage('Checkout') { steps { git url: 'https://github.com/MaximSlepukhin/bankapp.git', branch: 'feature/sprint-10' } }
        stage('Prepare kubeconfig') {
            steps {
                sh '''
                cp $ORIGINAL_KUBECONFIG $KUBECONFIG
                sed -i "s|/Users/maksim/.minikube|$MINIKUBE_HOME|g" $KUBECONFIG
                sed -i "s|127.0.0.1:[0-9]*|host.docker.internal:50049|g" $KUBECONFIG
                '''
            }
        }
        stage('Build with Maven') {
            agent {
                docker {
                    image 'maven:3.9.8-eclipse-temurin-21'
                    args "-v ${env.WORKSPACE}:${env.WORKSPACE} -w ${env.WORKSPACE}"
                }
            }
            steps { sh 'mvn clean package -DskipTests' }
        }
        stage('Build Docker Image') { steps { script { buildAndPush(env.SERVICE_NAME) } } }
        stage('Deploy to Kubernetes') { steps { sh "helm upgrade --install ${SERVICE_NAME} ${HELM_CHART_PATH} --namespace dev --kube-insecure-skip-tls-verify --wait" } }
    }

    post { always { sh 'docker ps -a' } }
}

def buildAndPush(service) {
    sh """
        workspace="/var/jenkins_home/workspace/BankCICD@2"
        jarPath="\$workspace/$service/target/${service}-1.0-SNAPSHOT.jar"
        if [ ! -f "\$jarPath" ]; then echo "JAR not found!"; exit 1; fi
        cp "\$jarPath" "\$workspace/$service/app.jar"
        docker build -t ${service}:latest "\$workspace/$service"
    """
}
