apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts.secretName" . }}
type: Opaque
stringData:
  POSTGRES_USERNAME: "{{ .Values.postgres.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  KEYCLOAK_CLIENT_SECRET: "{{ .Values.keycloak.client.secret }}"
