apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-db.fullname" . }}
  labels:
    app: {{ include "keycloak-db.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "keycloak-db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "keycloak-db.name" . }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
{{- if .Values.postgres.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.persistence.existingClaim }}
{{- else }}
          persistentVolumeClaim:
            claimName: {{ include "keycloak-db.fullname" . }}-data
{{- end }}
