replicaCount: 1

image:
  repository: cash-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8091
  labels:
    app.kubernetes.io/name: cash-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8091"

resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "200m"


env:
  SPRING_PROFILES_ACTIVE: "prod"

clients:
  accounts-service-url: "http://accounts-service:8081"
  blocker-service-url: "http://blocker-service:8087"
  notifications-service-url: "http://notifications-service:8087"

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: cash-service.local
      paths:
        - path: /
          pathType: Prefix