spring:
  application:
    name: blocker-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:80/realms/bank-realm/protocol/openid-connect/certs

server:
  port: 8087
  address: 0.0.0.0

blocker:
  maintenance:
    start: "00:00"
    end: "00:05"

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  metrics:
    enable:
      all: true

  tracing:
    sampling:
      probability: 1

  zipkin:
    tracing:
      endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans