spring:
  application:
    name: accounts-service

  kafka:
    bootstrap-servers: my-kafka.default.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:postgresql://accounts-db-accounts-db:5432/accountsdb?currentSchema=accounts_service
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: accounts_service

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: accounts_service

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8081
  shutdown: graceful

logging:
  level:
    root: INFO
    com.github.maximslepukhin: INFO
    org.springframework: WARN
    org.hibernate: WARN
    liquibase: WARN

management:
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    enable:
      all: true

  tracing:
    sampling:
      probability: 1

  zipkin:
    tracing:
      endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans
