spring:
  application:
    name: accounts-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: accounts_service

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/accounts-service/master.yaml
    default-schema: accounts_service
    drop-first: true
    clear-checksums: true

server:
  port: 8081
  address: 0.0.0.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/