spring:
  application:
    name: accounts-service

  datasource:
    url: jdbc:postgresql://accounts-db-accounts-db:5432/accountsdb?currentSchema=accounts_service
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: accounts_service

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: accounts_service

server:
  port: 8081

logging:
  level:
    root: INFO                   # общий уровень логов
    org.springframework: DEBUG    # Spring Boot: контекст, бины, DataSource
    liquibase: DEBUG              # все детали Liquibase
    org.hibernate.SQL: DEBUG      # показывать SQL, который выполняется
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # показать параметры SQL
