spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: accounts_service

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true
    clear-checksums: true
    default-schema: accounts_service     # схема для таблиц приложения
    liquibase-schema: accounts_service   # схема для служебных таблиц Liquibase
