apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-transfer-config
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"

  SPRING_DATASOURCE_URL: >
    jdbc:postgresql://{{ .Values.env.POSTGRES_HOST }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.env.POSTGRES_PORT }}/{{ .Values.env.POSTGRES_DATABASE }}?currentSchema={{ .Values.env.POSTGRES_SCHEMA }}

  SPRING_DATASOURCE_USERNAME: "{{ .Values.env.POSTGRES_USERNAME }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.env.POSTGRES_PASSWORD }}"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "{{ .Values.env.POSTGRES_SCHEMA }}"
  SPRING_LIQUIBASE_DEFAULT_SCHEMA: "{{ .Values.env.POSTGRES_SCHEMA }}"
  ACCOUNTS_SERVICE_URL: "{{ .Values.env.ACCOUNTS_SERVICE_URL }}"
  BLOCKER_SERVICE_URL: "{{ .Values.env.BLOCKER_SERVICE_URL }}"
  NOTIFICATIONS_SERVICE_URL: "{{ .Values.env.NOTIFICATIONS_SERVICE_URL }}"
  EXCHANGE_SERVICE_URL: "{{ .Values.env.EXCHANGE_SERVICE_URL }}"