apiVersion: v1
kind: Service
metadata:
  name: {{ include "transfer-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "transfer-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8083
      protocol: TCP
