accounts-service:
  enabled: true

blocker-service:
  enabled: true
  replicaCount: 1
  image:
    repository: blocker-service
    tag: latest
    pullPolicy: IfNotPresent
  env:
    maintenanceStart: "00:00"
    maintenanceEnd: "00:05"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"


cash-service:
  enabled: true

exchange-generator-service:
  enabled: true

exchange-service:
  enabled: true

front-ui:
  enabled: true

notifications-service:
  enabled: true

transfer-service:
  enabled: true

keycloak:
  enabled: true

accounts-db:
  enabled: true

keycloak-db:
  enabled: true
