accounts-service:
  enabled: true
  image:
    repository: localhost:5000/accounts-service
    tag: latest
    pullPolicy: IfNotPresent

blocker-service:
  enabled: true
  replicaCount: 1
  image:
    repository: localhost:5000/blocker-service
    tag: latest
    pullPolicy: IfNotPresent

cash-service:
  enabled: true
  image:
    repository: localhost:5000/cash-service
    tag: latest
    pullPolicy: IfNotPresent

exchange-generator-service:
  enabled: true
  image:
    repository: localhost:5000/exchange-generator-service
    tag: latest
    pullPolicy: IfNotPresent

exchange-service:
  enabled: true
  image:
    repository: localhost:5000/exchange-service
    tag: latest
    pullPolicy: IfNotPresent

front-ui:
  enabled: true
  image:
    repository: localhost:5000/front-ui
    tag: latest
    pullPolicy: IfNotPresent

notifications-service:
  enabled: true
  image:
    repository: localhost:5000/notifications-service
    tag: latest
    pullPolicy: IfNotPresent

transfer-service:
  enabled: true
  image:
    repository: localhost:5000/transfer-service
    tag: latest
    pullPolicy: IfNotPresent












    # values-dev.yaml
    springProfile: dev

    image:
      repository: exchange-generator-service
      pullPolicy: IfNotPresent
      tag: "latest"

    service:
      type: ClusterIP
      port: 8080

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
