apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blocker-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blocker-service
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - targetPort: 8087
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cash-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cash-service
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - targetPort: 8091
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exchange-generator-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: exchange-generator-service
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - targetPort: 8080
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exchange-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: exchange-service
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - targetPort: 8084
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front-ui-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: front-ui
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - targetPort: 8080
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notifications-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: notifications-service
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - targetPort: 8087
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transfer-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: transfer-service
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - targetPort: 8083
      path: /actuator/prometheus
      interval: 15s